version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: product_db
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=1234
      - POSTGRESQL_DATABASE=product_db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - app_network

  redis:
    image: bitnami/redis:latest
    container_name: product_redis
    environment:
      - REDIS_PASSWORD=1234
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis
    networks:
      - app_network
  zipkin:
    image: openzipkin/zipkin
    container_name: product_zipkin
    ports:
      - "9411:9411"
    networks:
      - app_network

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge