version: '3.8'

services:
  mysql:
    image: bitnami/mysql:latest
    container_name: product_db
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=msa_exam
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql
    networks:
      - app_network

  redis:
    image: bitnami/redis:latest
    container_name: product_redis
    environment:
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=systempass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis
    networks:
      - app_network
  zipkin:
    image: openzipkin/zipkin
    container_name: product_zipkin
    ports:
      - "9411:9411"
    networks:
      - app_network

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge