spring:
  application:
    name: auth

eureka:
  client:
    service-url:
      defaultZone: http://eureka-prod-server:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://zipkin-prod-server:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

service:
  jwt:
    access-expiration: 7200000
    secret-key: "${JWT_SECRET_KEY}"

server:
  port: 19095